### ISSUE TITLE
Test failures?

### ISSUE THREAD

**Issue by utkarsh2102** [chrisk/fakeweb#66]
```
┌──────────────────────────────────────────────────────────────────────────────┐
│ Run tests for ruby2.5 from debian/ruby-tests.rb                              │
└──────────────────────────────────────────────────────────────────────────────┘

RUBYLIB=/<<BUILDDIR>>/ruby-fakeweb-1.3.0+git20170806+dfsg1/debian/ruby-fakeweb/usr/lib/ruby/vendor_ruby:. GEM_PATH=debian/ruby-fakeweb/usr/share/rubygems-integration/all:/var/lib/gems/2.5.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all ruby2.5 debian/ruby-tests.rb
Loaded suite debian/ruby-tests
Started
...................................................F
===============================================================================
Failure: test_real_https_request(TestFakeWeb):
  not all expectations were satisfied
  unsatisfied expectations:
  - expected at least once, not yet invoked: #<Mock:SSLSocket>.session()
  satisfied expectations:
  - expected at least once, invoked once: #<Mock:SSLSocket>.read_nonblock(any_parameters)
  - expected exactly once, invoked once: #<Mock:SSLSocket>.write(all_of(includes("GET /main/rss/hotnews/hotnews.rss HTTP/1.1"), includes("Host: images.apple.com")))
  - allowed any number of times, invoked twice: #<Mock:SSLSocket>.close(any_parameters)
  - allowed any number of times, invoked 3 times: #<Mock:SSLSocket>.closed?(any_parameters)
  - allowed any number of times, invoked twice: #<Mock:SSLSocket>.setsockopt(any_parameters)
  - expected at least once, invoked twice: #<Mock:SSLSocket>.connect_nonblock(any_parameters)
  - allowed any number of times, invoked twice: #<Mock:SSLSocket>.sync_close=(any_parameters)
  - expected at least once, invoked twice: OpenSSL::SSL::SSLSocket.new(#<Mock:SSLSocket>, instance_of(OpenSSL::SSL::SSLContext))
  - expected at least once, invoked twice: OpenSSL::SSL::SSLSocket.===(#<Mock:SSLSocket>)
  - expected at least once, invoked twice: TCPSocket.open("images.apple.com", 443, nil, nil)
/<<BUILDDIR>>/ruby-fakeweb-1.3.0+git20170806+dfsg1/test/test_helper.rb:123:in `setup_expectations_for_real_request'
/<<BUILDDIR>>/ruby-fakeweb-1.3.0+git20170806+dfsg1/test/test_helper.rb:175:in `setup_expectations_for_real_apple_hot_news_request'
/<<BUILDDIR>>/ruby-fakeweb-1.3.0+git20170806+dfsg1/test/test_fake_web.rb:410:in `test_real_https_request'
     407: 
     408:   def test_real_https_request
     409:     FakeWeb.allow_net_connect = true
  => 410:     setup_expectations_for_real_apple_hot_news_request(:port => 443)
     411: 
     412:     http = Net::HTTP.new('images.apple.com', 443)
     413:     http.use_ssl = true
===============================================================================
...............................................................................
.............................................................
Finished in 0.254606772 seconds.
-------------------------------------------------------------------------------
192 tests, 353 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
99.4792% passed
-------------------------------------------------------------------------------
```

**Comment by utkarsh2102** [comment]
@davidcornu, was your PR related?

**Comment by davidcornu** [comment]
Hey @utkarsh2102. To my recollection, all the issues I addressed in my PR were fixed separately. This looks like another issue.

**Comment by utkarsh2102** [comment]
@davidcornu, could you possibly fix this as well? :x

**Comment by davidcornu** [comment]
As far as I can tell, this library is currently unmaintained (https://github.com/chrisk/fakeweb/issues/57). I made some fixes awhile back as I was working on an app that still relied on it but we've moved to [WebMock](https://github.com/bblimke/webmock) since.
